baseURL = "https://twv2.netlify.app"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
paginate = "5"
summaryLength = "50"
title = "Tropical White Villages | Estate Agent"
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[module.hugoVersion]
extended = true
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]
