################################### English language #####################################
[languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
# copyright
copyright = "Design By [Tropicaldo](https://tropicaldo.com/) Develop By [Tropicaldo](https://Tropicaldo.com/)"


################################### French language #####################################
[languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
# copyright
copyright = "Design By [Tropicaldo](https://Tropicaldo.com/) Develop By [Tropicaldo](https://Tropicaldo.com/)"

################################### Spanish language #####################################
[languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 3
home = "Volver"
# footer content
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
# copyright
copyright = "Design By [Tropicaldo](https://Tropicaldo.com/) Develop By [Tropicaldo](https://Tropicaldo.com/)"