[[footer]]
name = "Sur"
url = "fr/about"
weight = 1
[[footer]]
name = "Contact"
url = "fr/contact"
weight = 2
[[footer]]
name = "Politique de Confidentialité"
url = "fr/privacy-policy"
weight = 3
[[footer]]
name = "Termes et Conditions"
url = "fr/terms-conditions"
weight = 4
[[main]]
hasChildren = false
name = "Accueil"
weight = 1
[[main]]
name = "Sur"
url = "fr/about"
weight = 2
[[main]]
name = "Contact"
url = "fr/contact"
weight = 3
