[[footer]]
name = "Nosotras"
url = "about"
weight = 1
[[footer]]
name = "Contacto"
url = "contact"
weight = 2
[[footer]]
name = "Política de privacidad"
url = "privacy-policy"
weight = 3
[[footer]]
name = "Términos y Condiciones"
url = "terms-conditions"
weight = 4
[[main]]
hasChildren = false
name = "Casa"
weight = 1
[[main]]
name = "Nosotras"
url = "about"
weight = 2
[[main]]
name = "Contacto"
url = "contact"
weight = 3
[[main]]
hasChildren = true
name = "Paginas"
weight = 4
[[main]]
name = "Autora"
parent = "Paginas"
url = "author/catarina"
weight = 1
[[main]]
name = "Categoría"
parent = "Paginas"
url = "categories/photography"
weight = 2
[[main]]
name = "Etiquetas"
parent = "Paginas"
url = "tags/garden"
weight = 3
