[[footer]]
name = "About"
url = "about"
weight = 1
[[footer]]
name = "Contact"
url = "contact"
weight = 2
[[footer]]
name = "Privacy Policy"
url = "privacy-policy"
weight = 3
[[footer]]
name = "Terms Conditions"
url = "terms-conditions"
weight = 4
[[main]]
hasChildren = true
name = "homepage"
weight = 1
[[main]]
name = "Homepage Full Width"
parent = "homepage"
url = "homepage/full/"
weight = 1
[[main]]
name = "Homepage Full With Left Sidebar"
parent = "homepage"
url = "homepage/full-left/"
weight = 2
[[main]]
name = "Homepage Full With Right Sidebar"
parent = "homepage"
url = "homepage/full-right/"
weight = 3
[[main]]
name = "Homepage List Style"
parent = "homepage"
url = "homepage/list/"
weight = 4
[[main]]
name = "Homepage List With Left Sidebar"
parent = "homepage"
url = "homepage/list-left/"
weight = 5
[[main]]
name = "Homepage List With Right Sidebar"
parent = "homepage"
url = "homepage/list-right/"
weight = 6
[[main]]
name = "Homepage Grid Style"
parent = "homepage"
url = "homepage/grid/"
weight = 7
[[main]]
name = "Homepage Grid With Left Sidebar"
parent = "homepage"
url = "homepage/grid-left/"
weight = 8
[[main]]
name = "Homepage Grid With Right Sidebar"
parent = "homepage"
url = "homepage/grid-right/"
weight = 9
[[main]]
name = "About"
url = "about"
weight = 2
[[main]]
name = "Contact"
url = "contact"
weight = 3
[[main]]
hasChildren = true
name = "Pages"
weight = 4
[[main]]
name = "Author"
parent = "Pages"
url = "author/john-doe"
weight = 1
[[main]]
name = "Category"
parent = "Pages"
url = "categories/photography"
weight = 2
[[main]]
name = "Tags"
parent = "Pages"
url = "tags/photo"
weight = 3
[[main]]
name = "Search"
parent = "Pages"
url = "http://demo.gethugothemes.com/logbook/fr/search/?s=image"
weight = 4
[[main]]
name = "404 Page"
parent = "Pages"
url = "404"
weight = 5
[[main]]
name = "Elements"
parent = "Pages"
url = "elements/"
weight = 6
