[[footer]]
name = "Nosotras"
url = "es/about"
weight = 1
[[footer]]
name = "Contacto"
url = "es/contact"
weight = 2
[[footer]]
name = "Política de privacidad"
url = "es/privacy-policy"
weight = 3
[[footer]]
name = "Términos y Condiciones"
url = "es/terms-conditions"
weight = 4
[[main]]
hasChildren = false
name = "Casa"
weight = 1
[[main]]
name = "Nosotras"
url = "es/about"
weight = 2
[[main]]
name = "Contacto"
url = "es/contact"
weight = 3
[[main]]
hasChildren = true
name = "Paginas"
weight = 4
[[main]]
name = "Autora"
parent = "Paginas"
url = "es/author/catarina"
weight = 1
[[main]]
name = "Categoría"
parent = "Paginas"
url = "es/categories/solobrena"
weight = 2
[[main]]
name = "Etiquetas"
parent = "Paginas"
url = "es/tags/garden"
weight = 3
