[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/font-awesome/fontawesome.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/solid.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"
[params.variables]
black = "#000"
body_color = "#000"
border_color = "#ddd"
color_primary = "#ce8460"
font_primary = "Open Sans:wght@400"
font_primary_type = "sans-serif"
font_scale = "1.2"
font_secondary = "Montserrat:wght@400"
font_secondary_type = "sans-serif"
font_size = "16px"
icon_font = "Font Awesome 5 Free"
light = "#f0f0f0"
text_color = "#696c6d"
text_color_dark = "#1c1d1f"
text_color_light = "#888c8e"
white = "#fff"
