contact_form_action = "#"
custom_script = ""
email = "catarina@twv.es"
favicon = "images/favicon.png"
featured_post = true
image_gallery = true
logo = "images/logo.png"
logo_text = "Tropical White Villages"
logo_width = "240x"
mainSections = ["post"]
page_not_found_image = "images/404.png"
post_layout = "grid"
search = true
sidebar = "right"
[baidu]
analytics_id = ""
enable = false
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[matomo]
enable = false
id = ""
url = ""
[metadata]
author = "Tropicaldo"
description = "This is meta description"
image = "images/favicon.png"
keywords = ["Boilerplate", "Hugo", "GetHugoThemes"]
[plausible]
domain = ""
enable = false
[preloader]
enable = false
preloader = ""
[promotion]
button_label = "Get Started"
button_link = "https://themefisher.com/"
content = "Lorem ipsum dolor sit amet, consectetur sociis. Etiam nunc amet id dignissim. Feugiat id tempor vel sit ornare."
image = "images/promotion.jpg"
title = "Create Stunning Website!!"
[site_verification]
baidu = ""
bing = ""
facebook = ""
google = ""
[snipcart]
currency = "$"
enable = false
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
[subscription]
enable = true
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["search", "about-me", "promotion", "subscription", "categories", "recent-post", "tags", "social"]
[[social]]
icon = "fab fa-facebook"
link = "#"
name = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
name = "twitter"
[[social]]
icon = "fab fa-linkedin-in"
link = "#"
name = "linkedin"
[[social]]
icon = "fab fa-github"
link = "#"
name = "github"
